// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfpMd79bXfsK9awXSPiuhyxDIVt78AVgA',
    appId: '1:786229477053:web:7c94e2eec88908ec8fc1d4',
    messagingSenderId: '786229477053',
    projectId: 'e-store-6c923',
    authDomain: 'e-store-6c923.firebaseapp.com',
    storageBucket: 'e-store-6c923.appspot.com',
    measurementId: 'G-HNCT3MCPRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbDnczGU-IfhPe6-RHAKxdjy6cqwFDiZs',
    appId: '1:786229477053:android:1ba42f80e1c7c0658fc1d4',
    messagingSenderId: '786229477053',
    projectId: 'e-store-6c923',
    storageBucket: 'e-store-6c923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk6EElKLqCqy3z1Ue8kvoX2lONd0CKQe0',
    appId: '1:786229477053:ios:37dfa6eb00200cd38fc1d4',
    messagingSenderId: '786229477053',
    projectId: 'e-store-6c923',
    storageBucket: 'e-store-6c923.appspot.com',
    androidClientId: '786229477053-t2qaunuu9td917c42cshgsas2ikdsb1u.apps.googleusercontent.com',
    iosClientId: '786229477053-gko7ise33rrf6qltl4qb12ednn08h2e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk6EElKLqCqy3z1Ue8kvoX2lONd0CKQe0',
    appId: '1:786229477053:ios:37dfa6eb00200cd38fc1d4',
    messagingSenderId: '786229477053',
    projectId: 'e-store-6c923',
    storageBucket: 'e-store-6c923.appspot.com',
    androidClientId: '786229477053-t2qaunuu9td917c42cshgsas2ikdsb1u.apps.googleusercontent.com',
    iosClientId: '786229477053-gko7ise33rrf6qltl4qb12ednn08h2e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
